/**
 * @packageDocumentation
 * @module api.functional.novel.regist
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";

import { Body } from ".."

/**
 * @controller NovelController.registNovel
 * @path POST /novel/regist
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function registNovel(
  connection: IConnection,
  body: registNovel.Input,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...registNovel.METADATA,
      template: registNovel.METADATA.path,
      path: registNovel.path(),
    },
    body,
  );
}
export namespace registNovel {
  export type Input = Resolved<Body.IRegistNovelArgs>;

  export const METADATA = {
    method: "POST",
    path: "/novel/regist",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/novel/regist";
}
