/**
 * @packageDocumentation
 * @module api.functional.novel.list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";

import { Query } from "..";

/**
 * @controller NovelController.getNovelList
 * @path GET /novel/list
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getNovelList(
  connection: IConnection,
  query: getNovelList.Query,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...getNovelList.METADATA,
    template: getNovelList.METADATA.path,
    path: getNovelList.path(query),
  });
}
export namespace getNovelList {
  export type Query = Resolved<Query.IGetNovelList>;

  export const METADATA = {
    method: "GET",
    path: "/novel/list",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: getNovelList.Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/novel/list";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
