/**
 * @packageDocumentation
 * @module api.functional.requester.interest
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Resolved } from "typia";

import { Body } from ".."

/**
 * @controller RequesterController.registRequester
 * @path POST /requester/interest
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function registRequester(
  connection: IConnection,
  body: registRequester.Input,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...registRequester.METADATA,
      template: registRequester.METADATA.path,
      path: registRequester.path(),
    },
    body,
  );
}
export namespace registRequester {
  export type Input = Resolved<Body.IRegistRequesterArgs>;

  export const METADATA = {
    method: "POST",
    path: "/requester/interest",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/requester/interest";
}
